[package]
name = "RustGLM"
version = "0.1.4"
edition = "2021"
authors = ["blueokanna <blueokanna@gmail.com>"]
repository = "https://github.com/blueokanna/RustGLM.git"
license = "Apache-2.0"
description = "High-performance, Reliable Zhipu ChatGLM SDK nat